name: Deploy React App to GitHub Pages

# Run this workflow every time you push to the `main` branch
on:
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Set the permissions for the GitHub token so the Action can deploy
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository code
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Use a stable version of Node.js
          cache: "npm"
          cache-dependency-path: client/package-lock.json

      # Step 3: Install dependencies for your React app
      - name: Install Dependencies
        run: npm ci
        working-directory: ./client

      # Step 4: Build your React app for production
      - name: Build
        run: npm run build
        working-directory: ./client

      # Step 5: Prepare the build artifact for deployment
      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # This should be the folder your build command outputs to
          path: "./client/build"

      # Step 6: Deploy the artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
